name: CI for BaseCamp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Validate Ansible playbook syntax
        run: |
          ansible-playbook --syntax-check camp.yml

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible ansible-lint

      - name: Lint Ansible playbook
        run: |
          ansible-lint camp.yml
