name: Validate BaseCamp Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-camp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Validate camp.yml
        run: |
          ansible-playbook --syntax-check camp.yml

      - name: Run camp setup (test)
        run: |
          ansible-playbook --connection=local --inventory 127.0.0.1, camp.yml --ask-become-pass
