name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"  # Match this to your go.mod file

      - name: Build BaseCamp CLI
        run: |
          go build -o basecamp

      - name: Archive Binary
        run: |
          mkdir -p release
          mv basecamp release/basecamp
          tar -czf release/basecamp-linux-amd64.tar.gz -C release basecamp

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: basecamp-linux
          path: release/basecamp-linux-amd64.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/basecamp-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
