name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build BaseCamp CLI
        run: |
          go build -o basecamp

      - name: Archive Binary
        run: |
          mkdir -p release
          mv basecamp release/basecamp
          tar -czf release/basecamp-linux-amd64.tar.gz -C release basecamp

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/basecamp-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
